- spec/service_worker/index.html
This is following the discussion in https://github.com/slightlyoff/ServiceWorker/issues/588
CC @annevk  @jakearchibald
> WindowClient.focus() resolves with updated WindowClient.

- explainer.md
As far as I understand, `event.replace()` is abandoned in favor of `self.skipWaiting()`
> Mention self.skipWaiting() instead of event.replace()

- explainer.md
There's not much to this; I just noticed a typo and thought you might like to merge the fix.
> typo: excecution -> execution

- spec/service_worker/index.html
Argument seems to have been misspelled a couple of times in the spec, this fixes those.
> Fix spelling error: arguement -> argument

- spec/service_worker/index.html
My attempt to spec the API described in issue #684.
I don't think this is anywhere near ready to be merged yet (in only because as far as I know current master is still V1, and this definitely is a V2 feature), but a pull request seemed like the easiest way to have a place to discuss details of foreign fetch.
Also haven't updated the .ts file with these changes, but then that file seems to be rather out of date anyway. So not sure if that file is still being used?
> Start with trying to spec foreign fetch.

- foreign_fetch_explainer.md
- spec/service_worker/index.bs
- spec/service_worker/index.html
Sorry for the delay, here is my foreign fetch pull request for issue #684 again, with some of the changes @jungkees made to it already applied on top.
This updates the [spec](http://mkruisselbrink.github.io/ServiceWorker/spec/service_worker/) to add support for foreign fetch, and adds a separate [foreign fetch explainer document](https://github.com/mkruisselbrink/ServiceWorker/blob/foreign-fetch/foreign_fetch_explainer.md).
> Foreign fetch

- README.md
- explainer.md
- implementation_considerations.md
To reduce confusion, this patch also ensures that sentence case is used consistently for titles.
Note: this only affects the Markdown files.
Ref. https://github.com/slightlyoff/ServiceWorker/issues/705.
> Use “service worker” consistently

- spec/service_worker/index.bs
See https://github.com/whatwg/html/pull/1003. DO NOT MERGE until that is merged; I will ping this thread when that happens.
> Change "validate the response" to "process the response" to match HTML

- spec/service_worker/index.bs
- spec/service_worker/index.html
This is my [attempt](http://mkruisselbrink.github.io/ServiceWorker/spec/service_worker/#link-type-serviceworker) to specify the serviceworker link element and header type to address issue #685.
> Specify serviceworker link type for link element and link header.

- spec/service_worker/index.bs
- spec/service_worker/index.html
In https://github.com/whatwg/html/pull/1487, HTML's script-fetching algorithms were updated and improved. This aligns service worker, which is a heavy consumer of those algorithms, with those changes.
DO NOT MERGE YET. This relies on https://github.com/whatwg/html/pull/1487 first being merged, and then on a day or two for Shepherd to scrape HTML's newly-exported `<dfn>`s, and then I have to rebuild the .html. But feel free to review!!
> Update for changes to HTML's script-fetching algorithms

- spec/service_worker/index.bs
- spec/service_worker/index.html
The current description pretends that a ReadableStream can be passed from one realm to another, which is wrong. This change changes the description so that it creates a new ReadableStream  and passes Uint8Array objects from the old ReadableStream to the new one.
This is discussed at https://github.com/whatwg/fetch/issues/330. This change fixes #850 as well.
> Create a new ReadableStream in FetchEvent.respondWith

- CONTRIBUTING.md
- README.md
- implementation_considerations.md
@jungkees This will complement https://github.com/w3c/ServiceWorker/commit/eb7b112ac7055ff6afb4bb5a97ed72c4ac6c5c23 and updates the rest of the links (`s/slightlyoff/w3c/`).
> Change the rest of the links to the new repo

- explainer.md
"e.g." means "for example". "i.e." means "in other words". In this context, "i.e." makes more sense than "e.g."
> Replace e.g. with i.e.

- explainer.md
I personally think that:
```js
return cachedResponse || fetch(event.request);
```
makes it a lot more obvious what's going on as opposed to:
```js
return response || fetch(event.request);
```
I had to do a double take with `response` as at first glance it looked like the request was being made twice.
> Make cache example easier to understand

- docs/index.bs
- docs/index.html
I extracted out some more safe changes from #995. As you can see from the .html diff, there's not much difference; it's mostly just removing anchors blocks.
> Editorial: more link-defaults and anchors cleanup

- docs/index.bs
- docs/index.html
- docs/v1/index.bs
- docs/v1/index.html
This changes Handle Fetch and Handle Functional Event to invoke Soft
Update even if the service worker doesn't have any event listener
registered for the event. (Note that the cases where the request falls
back to network still do not trigger Soft Update.)
Fixes #905.
> Add more Soft Update on functional events

- docs/index.bs
- docs/index.html
This follows the analogous fix in https://github.com/whatwg/html/pull/2077 for HTML.
Ideally this should be merged after the HTML pull request, but in practice it should be fine either way, as the HTML PR is pretty straightforward and will likely be merged forthwith.
> Fix arguments to "fetch a classic worker script"

- docs/index.bs
- docs/index.html
- docs/v1/index.bs
- docs/v1/index.html
This adds a type attribute to Client interface. Before this, we could
only differentiate the WindowClient objects from Client objects. With
the type attribute, a client can be identified as one of window,
dedicated worker, and shared worker.
Fixes #1005.
> Add client.type

- docs/index.bs
- docs/index.html
- docs/v1/index.bs
- docs/v1/index.html
Before this, skipWaiting() promises when called multiple times on a
waiting worker had different behaviors among each other where the winner
waits unitl the Activate is complete while others don't. This makes the
behavior consistent by making the Activate be called only once. To
achieve that, this removes the steps in skipWaiting() that call the
Activate on a waiting worker (so promise resolves right away after
setting the skip waiting flag) and simplifies the call sites of the
Activate in the Install algorithm.
Related issue: #1015.
> Change behavior of skipWaiting()

- docs/index.bs
- docs/index.html
- docs/v1/index.bs
- docs/v1/index.html
This introduces service worker registration's use cache field and its
related APIs: options.useCache to register method and
registration.useCache for ServiceWorkerRegistration objects. This
changes the default cache mode of fetching SW scripts to "no-cache".
After the change, 24 hours limit and job's force bypass cache flag rules
are still enforced. register() method's options value set to
{ useCache: true } re-enables the previous default behavior provided
before this change.
Fixes #893 #894.
> Fetch service worker scripts with "no-cache" by default

- docs/index.bs
If I'm following the spec correctly, we weren't setting `no-cache` correctly on module-imported scripts. I think this fixes that.
> Ensuring no-cache is set on module imported scripts

- docs/index.bs
- docs/index.html
> (WIP) Navigation preload

- README.md
CONTRIBUTING.md had the right link, but this didn't.
Followup to commit 3d10320a49ca9cef533d3ca3b2b5ca7677076b36.
> Link to v1 in README.md

- explainer.md
If “Google Gears” was supposed to be a link (just as Dojo Offline/AppCache are), now it is one. Otherwise, I’d suggest to remove the lonely opening square bracket. ;)
> Fix incomplete link

- docs/index.bs
- docs/index.html
- docs/v1/index.bs
- docs/v1/index.html
(1) This changes the approach to unsetting the extendable events'
extensions allowed flag. This change introduced a reference count based
approach instead of the promise-copying-and-checking approach.
(2) This also extends the opportunities of the lifetime extension by
allowing calling waitUntil() within microtasks queued by the given
promise's Promise.prototype.then callbacks.
Related issues:
- https://github.com/w3c/ServiceWorker/issues/931 (1)
- https://github.com/w3c/ServiceWorker/issues/935 (2)
- https://github.com/w3c/ServiceWorker/issues/1039 (2)
> Improve handling of extend lifetime promises

- docs/index.bs
- docs/index.html
We probably ultimately want to add the extra options to
ForeignFetchOptions as discussed in #880, but for now just limiting
headers and methods to CORS safelisted values seems reasonable, and
matches chrome's implementation.
> Add check for CORS-safelisted methods and headers to foreign fetch.

- docs/index.bs
- docs/index.html
This splits the “Link type "serviceworker"” ≫ “Processing” section into
two sections with separate headings:
* Processing the Link header
* Processing the link element
It also includes a minor editorial change to add the word “or” in a
place where lack of it makes the text ambiguous; this sentence:
> When a serviceworker link’s link element is inserted into a document,
> a serviceworker link is created on a link element that is already in a
> document tree, or the href or scope attributes of the link element of a
> serviceworker link is changed, the user agent should run these steps
...could be read as saying:
> When a serviceworker link’s link element is inserted into a document,
> **then** a serviceworker link is created on a link element...
When what it actually seems to mean is:
> …
> Add specific Processing headings + minor editorial

- docs/index.bs
- docs/index.html
- docs/v1/index.bs
- docs/v1/index.html
This adds concepts and algorithms to track events (all service worker
events: lifecycle events, functional events, extendable message events)
that have pending extension promises so they can be used to check if the
registration's waiting worker can be promoted.
This also changes Install algorithm and related steps to match to the
implementations behavior. That is, instead of waiting for the promotion
condition in Install algorithm, newly introduced Try Activate algorithm
just tries to activate depending on the condition and return. Try
Activate is called when:
- A service worker is installed.
- The last client controlled by the existing active worker is unloaded.
- skipWaiting() is called.
- The extend lifetime promises for the existing active worker settle.
Related issue: #916.
> Improve Activate with Try Activate

- docs/index.bs
- docs/index.html
- docs/v1/index.bs
- docs/v1/index.html
Fixes https://github.com/whatwg/fetch/issues/303#issuecomment-265483054.
Related fetch PR https://github.com/whatwg/fetch/pull/435.
> Opt cache.add/addAll and importScripts out of a local service worker

- docs/index.bs
- docs/v1/index.bs
This rewrites ancestorOrigins using DOMStringList instead of FrozenArray
to USVString reflecting the changes in HTML.
Related pull request: https://github.com/whatwg/html/pull/2192.
Related issue: https://github.com/w3c/ServiceWorker/issues/1051.
> Use DOMStringList for ancestorOrigins

- docs/index.bs
- docs/index.html
- docs/v1/index.bs
- docs/v1/index.html
This is a follow-up change, to [1], which addresses the issues posed in
[2] and the comments afterwards.
This change makes the callers to the Clear Registration algorithm to
check if no client is using the registration and the registration's
associated service workers have no pending extended events before
invoking the algorithm. Unregister, Handle Service Worker Client Unload,
and the microtasks queued by the extension promises' settlement handlers
invoke Try Clear Registration.
Other error handling steps on registrations that have no associated
worker and Handle User Agent Shutdown invoke Clear Registration directly
as they do.
[1] https://github.com/w3c/ServiceWorker/commit/f1a1120ff07120a2e8f311fb61f429c9a74db1ef
[2] https://github.com/w3c/ServiceWorker/issues/916#issuecomment-23727206 …
> Introduce Try Clear Registration; Delay activation

- docs/index.bs
The spec says "A service worker registration has an associated
NavigationPreloadManager object" and this object never changes. This is
also true of Blink's implementation.
> Use [SameObject] for the navigationPreload attribute

- docs/index.bs
- docs/index.html
> Update StructuredCloneWithTransfer() usage

- docs/index.bs
- docs/index.html
A few other specs that have something similar:
https://fetch.spec.whatwg.org/
https://w3c.github.io/IndexedDB/
https://notifications.spec.whatwg.org/
https://xhr.spec.whatwg.org/
(Also removed trailing whitespace as a first commit)
> Add a link to web-platform-tests to the top of the spec

- docs/index.bs
- docs/index.html
The `Service-Worker` header is appended to the request's header list in
a prior algorithm step.
> Remove duplicate step from "Update" algorithm

- docs/index.bs
- docs/index.html
This is part of https://github.com/whatwg/html/pull/2530; see related links there for more information. Closes #1116.
It is on top of #1102, so that needs to be merged first. In addition, the HTML PR needs to be merged first so that the messageerror event type is actually defined somewhere; once that's done the Bikeshed HTML needs to be regenerated.
Also, this needs some tests, which I will write.
> Handle deserialization failures in postMessage()

- docs/index.bs
- docs/index.html
The previous structure for the `ready` algorithm involved a recursive
path through an "else" branch. This tended to obscure the fact that the
corresponding branch was *not* recursive and that the following steps
were indeed reachable.
Re-factor the algorithm to include fewer total branches and to contain
the recursion more tightly.
---
I recognize that this is pretty subjective, so I'll be satisfied with the
opinion of the editors, whatever that is.
> Editorial: Simplify `ready`

- docs/index.bs
- docs/index.html
- docs/v1/index.bs
- docs/v1/index.html
This patch adds an assertion in the Match Service Worker Registration
that the given URL and the matched URL are the same origin. This also
adds a note that the URL serializer serializes the URLs with a trailing
slash at the end of the origin part of the URLs.
Fixes #1118.
> Assert same-origin for registration matching

- docs/index.bs
- docs/index.html
- docs/v1/index.bs
- docs/v1/index.html
This patch moves the creation of a Request object and its associated
Headers object to a right place. It moves those steps from outside into
the task where the fetch event's request attribute is initialized.
Fixes #951.
> Fix fetchEvent.request initialization

- docs/index.bs
- docs/index.html
Set job properties based on the value of the like-named algorithm inputs
(not the job properties themselves).
---
Even after application of this patch, the language is still somewhat confusing
because the job properties and algorithm inputs continue to share the same
name. I think a better fix would be to re-name the algorithm inputs (maybe
simply by removing the word "flag"), but I'd like to hear from an editor about
that.
> Editorial: Correct value references

- docs/index.bs
- docs/index.html
Because the "closing" attribute is not referenced elsewhere within the
specification, this step may cause confusion for readers who are not
familiar with its origins in the Workers specification. Extend the
reference to include a hyperlink to that document.
(The "confusion" mentioned above was my own. See gh-1143.)
> Extend attribute ref with link to external spec

- docs/index.bs
- docs/index.html
* Add new section “Declaring a "serviceworker" Link header”
* Drop normative requirement to fire an error if link[workertype] value is
not a valid worker type; instead just abort without firing an error.
* Drop the partial interface IDL for the HTMLLinkElement interface (the
definitions for the IDL attributes have already been merged directly
into the HTMLLinkElement interface IDL definition in the HTML spec).
Fixes #1073
> Update the “Link type "serviceworker"” section

- docs/index.bs
- docs/index.html
- docs/v1/index.bs
- docs/v1/index.html
This changes Resolve Job Promise algorithm to use a right value for
equivalent job promises by specifying the value should be the one for
its relevant Realm.
Fixes #829.
> Use right value for Resolve Job Promise

- docs/index.bs
- docs/v1/index.bs
This change adds a guard to waitUntil() that disallows the extension of
the event that is not dispatched by the user agent.
Fixes #1040.
> Disallow waitUntil() of manually constructed events

- docs/index.bs
- docs/v1/index.bs
This change clarifies a job queue isn't owned by a service worker
registration and reflects the implementations more precisely by defining
the scope to job queue map struct. This also makes it use the queue
struct defined in Infra instead of the FIFO queue concept that didn't
have a concrete reference.
Fixes #1180.
> Define scope to job queue map struct

- docs/v1/index.bs
- docs/v1/index.html
We're seeing a lot of confusion around V1 and the nightly. As in, developers are linking to the V1 spec and wondering why they can't find particular features.
I've added a warning to the V1 spec. What do you think?
> Warn readers that V1 is missing features compared to the nightly

- docs/index.bs
Is this a valid way of handling this, in terms of https://github.com/whatwg/fetch/pull/523.
It seems too easy.
(I'll add the same to foreign fetch if this is 👍 )
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/ServiceWorker/fetch-abort.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/ServiceWorker/d0df742...b035492.html)
> Handing fetch termination

- docs/index.bs
- docs/v1/index.bs
This change adds a guard to put() and addAll() that blocks 206 responses
entering the cache.
Fixes #937.
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/ServiceWorker/not-allow-206-cache.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/ServiceWorker/1d8fc5a...e2f8f08.html)
> Block partial responses entering the cache

- docs/index.bs
- docs/v1/index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1243.html" title="Last updated on Dec 8, 2017, 6:52 PM GMT (d5f5306)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1243/979ead7...d5f5306.html" title="Last updated on Dec 8, 2017, 6:52 PM GMT (d5f5306)">Diff</a>
> Avoid array manipulation in parallel

- docs/index.bs
The navigate() can be resolved as null if If browsingContext’s Window
object’s environment settings object’s creation URL’s origin is not
the same as the service worker's origin[1].
[1] https://w3c.github.io/ServiceWorker/#ref-for-dom-windowclient-navigate
***
<a href="https://pr-preview.s3.amazonaws.com/romandev/ServiceWorker/pull/1253.html" title="Last updated on Dec 21, 2017, 1:50 AM GMT (eccf275)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1253/90c04cd...romandev:eccf275.html" title="Last updated on Dec 21, 2017, 1:50 AM GMT (eccf275)">Diff</a>
> Make the promise settlement type of WindowClient.navigate() nullable

- docs/index.bs
- docs/v1/index.bs
The spec and the implementations did not agree on the behavior: the spec
didn't remove fragment identifiers and had ServiceWorker.scriptURL and
ServiceWorkerRegistration.scope return urls without stripping them.
Chrome, Firefox, and Edge don't return fragments.
This changes the spec to remove the fragment indentifiers from the
script url and scope url given to register() method before storing them,
in order to match the implementations.
Fixes #1249.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1251.html" title="Last updated on Dec 20, 2017, 11:11 AM GMT (2cf9fc0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1251/90c04cd...2cf9fc0.html" title="Last updated on Dec 20, 2017, 11:11 AM GMT (2cf9fc0)">Diff</a>
> Remove fragment identifiers from script url and scope url

- docs/index.bs
- docs/v1/index.bs
To reflect the decision to not expose reserved clients
(https://github.com/w3c/ServiceWorker/issues/1216) and to spec
.resultingClientId and .targetClientId in Nightly only, this:
* Removes
- Client.reserved and its associated reserved state (V1, Nightly)
- ClientQueryOptions.includeReserved (V1, Nightly)
- FetchEvent.reservedClientId (V1)
- FetchEvent.targetClientId (V1)
- FetchEventInit.reservedClientId (V1)
- FetchEventInit.targetClientId (V1)
* Changes
- FetchEvent.reservedClientId to FetchEvent.resultingClientId (Nightly)
- FetchEventInit.reservedClientId to FetchEventInit.resultingClientId
(Nightly)
- Handle Fetch to set FetchEvent.clientId for a navigation request to
the empty string (V1)
* Corrects
- matchedClients with clientObjects in Clients.matchAll() (V1, Nightly)
Related …
> Clean up Client API to not expose reserved clients

- docs/index.bs
WebIDL recently introduced dedicated syntax for mixins [1]. So, this
change replaces the existing `implements` with `includes` as per the new
concept.
[1] https://github.com/heycam/webidl/commit/45e8173d40ddff8dcf81697326e094bcf8b92920
***
<a href="https://pr-preview.s3.amazonaws.com/romandev/ServiceWorker/pull/1252.html" title="Last updated on Dec 21, 2017, 1:49 AM GMT (4512b72)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1252/90c04cd...romandev:4512b72.html" title="Last updated on Dec 21, 2017, 1:49 AM GMT (4512b72)">Diff</a>
> Use Web IDL's new-ish interface mixins concept

- docs/index.bs
- docs/index.html
- docs/v1/index.bs
- docs/v1/index.html
This change includes/considers the following:
- Include imported scripts to byte-check (for classic scripts).
- Compare responses' body instead of source text as per https://github.com/whatwg/html/issues/3316.
- Handle duplicate importScripts() as per https://github.com/w3c/ServiceWorker/issues/1041.
- Replace *imported scripts updated flag* referenced in importScripts()
by using service worker's state item.
- Have Update's perform the fetch steps cover module scripts.
- Avoid dobule-download of imported scripts pointed out in https://github.com/w3c/ServiceWorker/pull/1023#discussion_r92201798.
This change basically makes it check out if the main script resource is
identical to the existing resource. If so, it returns; otherwise, it
creates a new service worker and evalute it to check out …
> Improve service worker script caching and update

- docs/index.bs
- docs/v1/index.bs
This change addresses the issue described in the second paragraph of
https://github.com/w3c/ServiceWorker/issues/1042#issuecomment-270043959.
This change gets |destination| variable initialized to null if the
ServiceWorkerContainer object does not exist.
Fixes #1042.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1274.html" title="Last updated on Feb 12, 2018, 2:45 AM GMT (f6def65)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1274/49f954f...f6def65.html" title="Last updated on Feb 12, 2018, 2:45 AM GMT (f6def65)">Diff</a>
> Clarify target object of Client.postMessage can be null

- docs/index.bs
- docs/v1/index.bs
Before this change, .ready method was waiting for the change of the
state of the regisration's active worker without being synchronized with
the steps that set the corresponding ServiceWorkerRegistration object's
active ServiceWorker object's state.
This changes both .ready and Activate such that .ready tries to resolve
the ready promise, if pending, and just returns. And Activate resolves
pending ready promises after updating active ServiceWorker object's
state.
Fixes #1011
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1277.html" title="Last updated on Feb 12, 2018, 6:12 AM GMT (77eb154)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1277/49f954f...77eb154.html" title="Last updated on Feb 12, 2018, 6:12 AM GMT (77eb154)">Diff</a>
> Improve.ready and Activate

- docs/index.bs
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/ServiceWorker/preload-optional.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/ServiceWorker/c577b77...5b1ff00.html)
> FetchEvent init preloadResponse should be optional. Fixes #1114.

- docs/index.bs
- docs/v1/index.bs
This is a fix for https://github.com/w3c/ServiceWorker/issues/1196.
I took inspiration from [fire an event](https://dom.spec.whatwg.org/#concept-event-fire).
This should clear up the confusion around realms and it make it easier for other specs.
@jungkees if you're happy with this, I'll port this to V1 and submit PRs to the specs that fire functional events.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1199.html" title="Last updated on Jun 21, 2018, 1:05 PM GMT (2c85816)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1199/657540a...2c85816.html" title="Last updated on Jun 21, 2018, 1:05 PM GMT (2c85816)">Diff</a>
> Making functional events simpler

- docs/v1/index.bs
`AbstractWorker` is an `interface mixin`, not an `interface`, so needs to be pull in via `includes` not `implements`.
Found while authoring https://github.com/web-platform-tests/wpt/pull/11960
> Fix syntax error in IDL

- docs/index.bs
To match https://github.com/whatwg/fetch/pull/781.
@ricea
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/ServiceWorker/pull/1338.html" title="Last updated on Aug 13, 2018, 2:50 AM GMT (fcd5787)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1338/73f5551...jyasskin:fcd5787.html" title="Last updated on Aug 13, 2018, 2:50 AM GMT (fcd5787)">Diff</a>
> Update the strategy argument to 'construct a ReadableStream'.

- docs/index.bs
We had decided (and I forgot) to change the name of FetchEvent.targetClientId to
.replacesClientId to clarify the meaning that this client is a to be replaced
client: https://github.com/w3c/ServiceWorker/issues/1091#issuecomment-342569083.
Related issue: https://github.com/w3c/ServiceWorker/issues/1245.
Fetch PR: https://github.com/whatwg/fetch/pull/774.
HTML PR: https://github.com/whatwg/html/pull/3788.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1333.html" title="Last updated on Jul 1, 2018, 11:25 PM GMT (b6bb29b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1333/ff36205...b6bb29b.html" title="Last updated on Jul 1, 2018, 11:25 PM GMT (b6bb29b)">Diff</a>
> Change name from targetClientId to replacesClientId

- docs/index.bs
- docs/v1/index.bs
Currently it's impossible for another spec to know if an extendable event is in progress, or what the result was afterwards.
I intended to just mark some things as "export", but tried to tidy up the useage along the way.
* `ExtendableEvent`'s **extend lifetime promises** is now exported.
* `ExtendableEvent` now has a  **timed out flag**, which makes the user agent timeout a little more formal and detectable by other specs.
* `ExtendableEvent` now has an **active** 'getter', which indicates the event is in progress.
If this is ok, I'll make the same changes in v1.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1348.html" title="Last updated on Sep 12, 2018, 9:57 AM GMT (4706c45)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1348/59c46 …
> Making it easier to handle the state of extendable events

- docs/index.bs
- docs/v1/index.bs
We have a somewhat similar `matchAll` method in background fetch https://wicg.github.io/background-fetch/#background-fetch-registration and I'd like to use the same matching we use in service worker.
I've abstracted out the part that can determine true/false for a request and a stored request/response. In background fetch we may not have the response yet, so it's optional.
If you're happy with this PR, I'll port it to v1.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1341.html" title="Last updated on Sep 12, 2018, 10:11 AM GMT (da43529)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1341/59c46fb...da43529.html" title="Last updated on Sep 12, 2018, 10:11 AM GMT (da43529)">Diff</a>
> Abstracting cache matching

- docs/index.bs
- docs/v1/index.bs
This change adds Client.frameType back with the reasons:
- Implementations maintain it.
- It can be accessed outside of fetch event handlers
This change also improved the steps of the algorithms that Create Window Client
invokes by removing unnecessary parallel steps.
Fixes: https://github.com/w3c/ServiceWorker/issues/732.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1329.html" title="Last updated on Jun 26, 2018, 5:35 AM GMT (3c7ff5c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1329/ff36205...3c7ff5c.html" title="Last updated on Jun 26, 2018, 5:35 AM GMT (3c7ff5c)">Diff</a>
> Add Client.frameType back

- docs/index.bs
The HTML standard returns Completion Records to convey the result
of running a script. Use that.
***
<a href="https://pr-preview.s3.amazonaws.com/mattto/ServiceWorker/pull/1346.html" title="Last updated on Oct 31, 2018, 7:06 AM GMT (88020ac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1346/7b85d13...mattto:88020ac.html" title="Last updated on Oct 31, 2018, 7:06 AM GMT (88020ac)">Diff</a>
> Clarify "uncaught runtime script error".

- docs/index.bs
...and so extensions should use [`partial interface mixin`](https://heycam.github.io/webidl/#partial-interface-mixin) rather than `partial interface`.
See also https://github.com/whatwg/html/pull/3650
***
<a href="https://pr-preview.s3.amazonaws.com/saschanaz/ServiceWorker/pull/1309.html" title="Last updated on May 4, 2018, 3:54 AM GMT (c5fa3a3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1309/9a6b738...saschanaz:c5fa3a3.html" title="Last updated on May 4, 2018, 3:54 AM GMT (c5fa3a3)">Diff</a>
> WindowOrWorkerGlobalScope is a mixin

- docs/index.bs
- In the "perform the fetch" steps for importScripts(), return the
response, not its unsafe response. These steps run inside "fetch a
classic worker-imported script"[1], which extract the unsafe response,
so getting the unsafe response twice is redundant or wrong.
- Extract a "network error import scripts" definition for resuability.
- Rename variables to avoid shadowing.
- Skip fetching the main resource again, when doing the import scripts
update check.
- Make the "perform the fetch" steps in Update asynchronously
complete with a response rather than returning true, as is expected
of these steps.[2]
[1] https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-classic-worker-imported-script
[2] https://html.spec.whatwg.org/multipage/webappapis.html#fetching-scripts-perform-fetch …
> Minor improvements around importScripts.

- docs/index.bs
- docs/index.html
As asked in https://github.com/w3c/ServiceWorker/commit/b67c4450e04e12e12777eebbb27c368a25263bc7#r33398873, the `environment` was referenced to `FileAPI` and it's good to refer to the `environment` in html spec directly.
cc @mkruisselbrink
***
<a href="https://pr-preview.s3.amazonaws.com/CYBAI/ServiceWorker/pull/1404.html" title="Last updated on May 4, 2019, 4:14 AM UTC (08350b2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1404/13c1a67...CYBAI:08350b2.html" title="Last updated on May 4, 2019, 4:14 AM UTC (08350b2)">Diff</a>
> Fix environment reference

- docs/index.bs
* Require Service-Worker-Allowed to be same-origin to the script URL
(#1307)
* Add non-normative explanation of Service-Worker-Allowed (#1405) and
other mitigations. The text is highly inspired by
https://infrequently.org/2014/12/psa-service-workers-are-coming/.
***
<a href="https://pr-preview.s3.amazonaws.com/mattto/ServiceWorker/pull/1409.html" title="Last updated on May 29, 2019, 12:56 AM UTC (0eadf93)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1409/86d9414...mattto:0eadf93.html" title="Last updated on May 29, 2019, 12:56 AM UTC (0eadf93)">Diff</a>
> Refinements and description of Service-Worker-Allowed.

- docs/index.bs
This makes the following changes:
* updateViaCache is a live property. This is covered by the WPT
registration-updateviacache.https.html. However we are missing tests for a
register() that rejects with a new updateViaCache property. The desired
behavior is to only update the property if register() resolves.
* Changing worker type bypasses the byte-for-byte update check. This is covered
by WPT update-registration-with-type.https.html.
* Adds Worker type and updateViaCache to the job equivalence check. This
probably can have a WPT for successive register() calls that vary these
properties don’t get coalesced into a single job.
Addresses #1189, #1408, #1359, and #1358.
***
<a href="https://pr-preview.s3.amazonaws.com/mattto/ServiceWorker/pull/1411.html" title="Last updated on Jun 3, 2019, …
> Improve "update via cache" and "worker type" in register algorithms.

- docs/index.bs
- docs/v1/index.bs
This makes {install,activate,fetch,message} events and
functional events use the same algorithm to determine
whether to skip firing the event, and makes it a *may*
rather than *must*.
It also unifies the concept of a stale registration to reduce
duplicated text.
Addresses #1200
***
<a href="https://pr-preview.s3.amazonaws.com/mattto/ServiceWorker/pull/1417.html" title="Last updated on Jun 6, 2019, 3:41 AM UTC (be8eb55)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1417/7f2b6e1...mattto:be8eb55.html" title="Last updated on Jun 6, 2019, 3:41 AM UTC (be8eb55)">Diff</a>
>  Unify the event skipping algorithm when there is no event handler.

- docs/index.bs
- docs/v1/index.bs
Fixes https://github.com/w3c/ServiceWorker/issues/1204.
Tests https://github.com/web-platform-tests/wpt/pull/17139.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1415.html" title="Last updated on Jun 4, 2019, 5:59 AM UTC (88f1b6a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1415/c1f3619...88f1b6a.html" title="Last updated on Jun 4, 2019, 5:59 AM UTC (88f1b6a)">Diff</a>
> Kill resurrection

- docs/index.bs
- docs/v1/index.bs
In the "Service-Worker-Allowed" section of the docs, there's an example of what the default scope would be for a service worker that's registered at `/js/sw.js`. The examples incorrectly state that the default scope would be `/js`, when it's actually `/js/`. (`/js` is one level higher than the default, maximum allowed scope of `/js/`.)
***
<a href="https://pr-preview.s3.amazonaws.com/jeffposnick/ServiceWorker/pull/1422.html" title="Last updated on Jun 7, 2019, 6:20 AM UTC (c0b48e1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1422/f03b6d1...jeffposnick:c0b48e1.html" title="Last updated on Jun 7, 2019, 6:20 AM UTC (c0b48e1)">Diff</a>
> Add trailing '/' to example of max scope

- docs/index.bs
- docs/v1/index.bs
@mattto nothing new here apart from that "context object" thing you mentioned.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1428.html" title="Last updated on Jun 7, 2019, 2:49 PM UTC (e972737)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1428/94e6a67...e972737.html" title="Last updated on Jun 7, 2019, 2:49 PM UTC (e972737)">Diff</a>
> One ServiceWorker object per service worker per realm

- docs/index.bs
- docs/v1/index.bs
This cleans up Run Service Worker to block until the worker is running or fails to start. If running, the Completion record is stashed in a new variable. Callsites are updated to check if the worker is running before proceeding. It also disallows starting a redundant worker. postMessage is dropped silently if starting the service worker failed.
Addresses #1146 and #1403.
***
<a href="https://pr-preview.s3.amazonaws.com/mattto/ServiceWorker/pull/1419.html" title="Last updated on Jun 10, 2019, 1:35 AM UTC (b729b47)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1419/d65ed67...mattto:b729b47.html" title="Last updated on Jun 10, 2019, 1:35 AM UTC (b729b47)">Diff</a>
> Check for Run Service Worker failure and disallow starting redundant workers.

- docs/index.bs
- docs/v1/index.bs
* Make the parameter |linkable|.
* Add a space between "import" and "scripts".
***
<a href="https://pr-preview.s3.amazonaws.com/mattto/ServiceWorker/pull/1430.html" title="Last updated on Jun 11, 2019, 6:16 AM UTC (cf4bfb2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1430/5059261...mattto:cf4bfb2.html" title="Last updated on Jun 11, 2019, 6:16 AM UTC (cf4bfb2)">Diff</a>
> Bikeshed improvements to *force bypass cache for import scripts flag*

- docs/index.bs
- docs/v1/index.bs
Making service worker state a string internally, which simplifies setting it. Also ensuring that `.state` is set when we create service worker objects.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1432.html" title="Last updated on Jun 12, 2019, 8:32 AM UTC (2f2aac9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1432/c04359b...2f2aac9.html" title="Last updated on Jun 12, 2019, 8:32 AM UTC (2f2aac9)">Diff</a>
> Improving service worker state

- docs/index.bs
- docs/v1/index.bs
Turns out the only part of Clear Registration that was useful here was removing the item from the map, as the registrations are already empty at this point. I replaced the calls with removing the registration from the map.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1434.html" title="Last updated on Jun 13, 2019, 1:17 PM UTC (ad8bc13)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1434/7e17924...ad8bc13.html" title="Last updated on Jun 13, 2019, 1:17 PM UTC (ad8bc13)">Diff</a>
> Removing failed registrations

- docs/index.bs
- docs/v1/index.bs
This patch makes it to use ASCII serialization for
(Extendable)MessageEvent.origin instead of Unicode serialization which
has been removed from HTML.
HTML issue: https://github.com/whatwg/html/issues/2568.
HTML change: https://github.com/whatwg/html/pull/2689/commits/c3b2511ee0158fa4b5bd4e4689c6be54132f3d90.
Fixes #1142.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1151.html" title="Last updated on Jun 13, 2019, 5:57 PM UTC (7c0a94c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1151/9a74fc0...7c0a94c.html" title="Last updated on Jun 13, 2019, 5:57 PM UTC (7c0a94c)">Diff</a>
> Use ASCII serialization for origins

- docs/index.bs
Fixes #1077.
Tests https://github.com/web-platform-tests/wpt/pull/17285
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1426.html" title="Last updated on Jun 12, 2019, 9:14 AM UTC (ad80aea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1426/7e17924...ad80aea.html" title="Last updated on Jun 12, 2019, 9:14 AM UTC (ad80aea)">Diff</a>
> Adding self.serviceWorker to service workers.

- docs/index.bs
- docs/v1/index.bs
As I did with service worker objects, I made it more formal with registrations too.
I'll merge to v1 once we're happy with this.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1445.html" title="Last updated on Jun 28, 2019, 3:06 PM UTC (6c1d16e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1445/5580c1d...6c1d16e.html" title="Last updated on Jun 28, 2019, 3:06 PM UTC (6c1d16e)">Diff</a>
> How to create registration objects

- docs/index.bs
- docs/v1/index.bs
The Update algorithm step 9 has two issues:
- Using to-be-created environment settings object instead of a concrete
environment settings object
- Passing null value of job's client to the fetch a script algorithms in HTML
This change leaves notes on these issues to track them in the nightly version
and moves them to the Version 2 milestone in the github repository.
For https://github.com/w3c/ServiceWorker/issues/1013.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1450.html" title="Last updated on Jul 15, 2019, 8:44 PM UTC (5ff18bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1450/7c07a47...5ff18bd.html" title="Last updated on Jul 15, 2019, 8:44 PM UTC (5ff18bd)">Diff</a>
> Leave notes on service worker script fetching for V1

- docs/index.bs
- docs/v1/index.bs
This is part of heycam/webidl#758
heycam/webidl#750 introduces the change that use `{}` as default value for optional dictionaries.
***
<a href="https://pr-preview.s3.amazonaws.com/CYBAI/ServiceWorker/pull/1448.html" title="Last updated on Aug 9, 2019, 10:48 AM UTC (e4bf188)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1448/7c07a47...CYBAI:e4bf188.html" title="Last updated on Aug 9, 2019, 10:48 AM UTC (e4bf188)">Diff</a>
> Set default value of optional dictionary to {}

- docs/index.bs
- docs/v1/index.bs
This introduces the concept, service worker events, to refer to the events that
are one of lifecycle events, functional events, and the legacy message events
dispatched to ServiceWorkerGlobalScope.
Related PR: https://github.com/whatwg/dom/pull/653.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1452.html" title="Last updated on Jul 20, 2019, 12:25 AM UTC (85600fc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1452/2e2d872...85600fc.html" title="Last updated on Jul 20, 2019, 12:25 AM UTC (85600fc)">Diff</a>
> Define service worker events

- docs/index.bs
- docs/v1/index.bs
This change makes it clear that this behavior needs to be (and will be)
specified normatively in HTML Standard, and any future changes for Service
Workers will be incorporated into Service Workers Nightly. It also clarifies,
non-normatively, the behavior of how a service worker client's active service
worker is determined.
Issue: https://github.com/w3c/ServiceWorker/issues/765.
This moves the issue to the next milestone.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1455.html" title="Last updated on Aug 9, 2019, 4:33 PM UTC (983d3ea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1455/2e2d872...983d3ea.html" title="Last updated on Aug 9, 2019, 4:33 PM UTC (983d3ea)">Diff</a>
> Clarify determination of active service worker and spec plan

- docs/index.bs
- docs/v1/index.bs
Removing a redundant period.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1459.html" title="Last updated on Aug 14, 2019, 4:18 PM UTC (dd5819f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1459/2183f5e...dd5819f.html" title="Last updated on Aug 14, 2019, 4:18 PM UTC (dd5819f)">Diff</a>
> Fix a typo

- docs/index.bs
- docs/v1/index.bs
Activation handlers may not all get a chance to run, especially in the
case of browser termination.  A Service Worker should be designed to
function properly, even if the activation handlers do not all complete
successfully.
Update Nightly and V1
Closes https://github.com/w3c/ServiceWorker/issues/1372
***
<a href="https://pr-preview.s3.amazonaws.com/josephliccini/ServiceWorker/pull/1451.html" title="Last updated on Jul 19, 2019, 4:31 PM UTC (013a32c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1451/2e2d872...josephliccini:013a32c.html" title="Last updated on Jul 19, 2019, 4:31 PM UTC (013a32c)">Diff</a>
> Add a note about termination during activation.

- docs/index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1476.html" title="Last updated on Oct 8, 2019, 6:23 PM UTC (951c52e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1476/24be908...951c52e.html" title="Last updated on Oct 8, 2019, 6:23 PM UTC (951c52e)">Diff</a>
> Export ServiceWorkerGlobalScope's service worker for DOM Standards

- docs/index.bs
It seems inconsistent to use ExtendableMessageEvent for message events but not for messageerror events. This fixes that inconsistency.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1485.html" title="Last updated on Nov 21, 2019, 11:16 PM UTC (5b2b076)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1485/ffdd6c0...5b2b076.html" title="Last updated on Nov 21, 2019, 11:16 PM UTC (5b2b076)">Diff</a>
> Use ExtendableMessageEvent for messageerror in service workers.

- docs/index.bs
https://github.com/whatwg/fetch/pull/948/files is changing `<embed>` and `<object>` requests to
look more like navigations than subresource requests. As a result, it seems reasonable for service
worker to explicitly carve out those request destinations which have behavior service worker cares
about, rather than relying on a fetch-level concept that doesn't make sense in the new model.
I believe this is an editorial change without any behavior modification.
***
<a href="https://pr-preview.s3.amazonaws.com/mikewest/ServiceWorker/pull/1486.html" title="Last updated on Nov 25, 2019, 8:52 AM UTC (33abec1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1486/ffdd6c0...mikewest:33abec1.html" title="Last updated on Nov 25, 2019, 8:52 AM UTC (33abec1)">Diff</a>
> Drop 'potential-navigation-or-subresource request'.

- docs/index.bs
Fixes #1493
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1494.html" title="Last updated on Jan 9, 2020, 12:00 PM UTC (a235a64)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1494/7c23924...a235a64.html" title="Last updated on Jan 9, 2020, 12:00 PM UTC (a235a64)">Diff</a>
> Rewriting abstract

- docs/index.bs
Follows https://github.com/whatwg/html/pull/5411.
This moves to the imperative style of agent allocation, as HTML is no longer declaratively defining service worker agents and their relations to others.
***
<a href="https://pr-preview.s3.amazonaws.com/domenic/ServiceWorker/pull/1508.html" title="Last updated on Apr 6, 2020, 9:45 PM UTC (ebbc2b1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1508/5c6d27b...domenic:ebbc2b1.html" title="Last updated on Apr 6, 2020, 9:45 PM UTC (ebbc2b1)">Diff</a>
> Update agent and realm allocation

- docs/index.bs
This is part of https://github.com/whatwg/html/pull/5454.
- Define embedder policy in environment settings object for service
workers.
- Add the CORP check in #dom-cache-matchall.
Closes #1490 and whatwg/fetch#985.
***
<a href="https://pr-preview.s3.amazonaws.com/yutakahirano/ServiceWorker/pull/1516.html" title="Last updated on Jun 10, 2020, 1:16 PM UTC (65484fc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1516/0aceaac...yutakahirano:65484fc.html" title="Last updated on Jun 10, 2020, 1:16 PM UTC (65484fc)">Diff</a>
> Introduce Cross-Origin Embedder Policy

- docs/index.bs
* Uses "getter steps" and "method steps"
* Use "this" instead of "context object"
* Talk about dictionaries as Infra maps
* Minor restructuring of promise-creation/in parallel algorithms for NavigationPreloadManager
***
<a href="https://pr-preview.s3.amazonaws.com/domenic/ServiceWorker/pull/1528.html" title="Last updated on Aug 6, 2020, 8:58 AM UTC (2a02128)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1528/fc328f8...domenic:2a02128.html" title="Last updated on Aug 6, 2020, 8:58 AM UTC (2a02128)">Diff</a>
> Editorial: update to modern Web IDL conventions

- docs/index.bs
Part of https://github.com/whatwg/fetch/issues/1062. Also sets the new-ish fields on environments.
***
<a href="https://pr-preview.s3.amazonaws.com/domenic/ServiceWorker/pull/1527.html" title="Last updated on Aug 4, 2020, 5:50 PM UTC (3db93e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1527/fc328f8...domenic:3db93e2.html" title="Last updated on Aug 4, 2020, 5:50 PM UTC (3db93e2)">Diff</a>
> Update environment settings object creation

- docs/index.bs
Follows https://github.com/whatwg/streams/pull/1073.
Do not merge until that PR is merged. But, feel free to review.
See also https://github.com/tabatkins/bikeshed/issues/1758.
***
<a href="https://pr-preview.s3.amazonaws.com/domenic/ServiceWorker/pull/1533.html" title="Last updated on Sep 15, 2020, 2:16 PM UTC (a483802)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1533/e4c2953...domenic:a483802.html" title="Last updated on Sep 15, 2020, 2:16 PM UTC (a483802)">Diff</a>
> Use new Streams algorithms

- docs/index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/yutakahirano/ServiceWorker/pull/1563.html" title="Last updated on Feb 18, 2021, 4:09 AM UTC (40e9e10)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1563/044cc99...yutakahirano:40e9e10.html" title="Last updated on Feb 18, 2021, 4:09 AM UTC (40e9e10)">Diff</a>
> Have "Handle Fetch" return error when request's streaming body is unusable

- docs/index.bs
Thanks to https://github.com/heycam/webidl/pull/906.
***
<a href="https://pr-preview.s3.amazonaws.com/saschanaz/ServiceWorker/pull/1559.html" title="Last updated on Feb 4, 2021, 7:57 PM UTC (0125a86)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1559/044cc99...saschanaz:0125a86.html" title="Last updated on Feb 4, 2021, 7:57 PM UTC (0125a86)">Diff</a>
> Use undefined union for getRegistration()/match()/get()

- docs/index.bs
And link to the correct "origin" definition.
***
<a href="https://pr-preview.s3.amazonaws.com/mfalken/ServiceWorker/pull/1568.html" title="Last updated on Mar 5, 2021, 7:04 AM UTC (0e2ea19)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1568/9b66caa...mfalken:0e2ea19.html" title="Last updated on Mar 5, 2021, 7:04 AM UTC (0e2ea19)">Diff</a>
> Use "same origin" definition.

- docs/index.bs
Addresses #1573
***
<a href="https://pr-preview.s3.amazonaws.com/mfalken/ServiceWorker/pull/1583.html" title="Last updated on Apr 16, 2021, 8:03 AM UTC (556c1f8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1583/62db59f...mfalken:556c1f8.html" title="Last updated on Apr 16, 2021, 8:03 AM UTC (556c1f8)">Diff</a>
> Add note that chunking is not preserved with ReadableStream.

- docs/index.bs
to report worker-specific timing information to Navigation Timing.
In preparation for https://github.com/w3c/ServiceWorker/pull/1575
***
<a href="https://pr-preview.s3.amazonaws.com/noamr/ServiceWorker/pull/1581.html" title="Last updated on Apr 15, 2021, 1:11 PM UTC (2f50de4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1581/62db59f...noamr:2f50de4.html" title="Last updated on Apr 15, 2021, 1:11 PM UTC (2f50de4)">Diff</a>
> Expose a "service worker timing info" struct

- docs/index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/noamr/ServiceWorker/pull/1590.html" title="Last updated on Apr 29, 2021, 9:48 AM UTC (5f55eaf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1590/b807be1...noamr:5f55eaf.html" title="Last updated on Apr 29, 2021, 9:48 AM UTC (5f55eaf)">Diff</a>
> Service worker struct should be exported without a 'for' attribute

- docs/index.bs
This is a companion PR to https://github.com/whatwg/html/pull/6504, which adds the concept of a policy container and attaches it to the environment settings object and the WorkerGlobalScope. This PR correctly initializes the policy container of the underlying WorkerGlobalScope of a ServiceWorkerGlobalScope.
***
<a href="https://pr-preview.s3.amazonaws.com/antosart/ServiceWorker/pull/1588.html" title="Last updated on Apr 27, 2021, 11:25 AM UTC (28aafd2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1588/d26edf9...antosart:28aafd2.html" title="Last updated on Apr 27, 2021, 11:25 AM UTC (28aafd2)">Diff</a>
> Adapt to policy container

- docs/index.bs
This is a companion PR to https://github.com/w3c/webappsec-csp/pull/493. That PR requires calling the check for blocking ServiceWorkers which try to enforce sandboxing via CSP directly from ServiceWorker.
***
<a href="https://pr-preview.s3.amazonaws.com/antosart/ServiceWorker/pull/1591.html" title="Last updated on May 5, 2021, 11:57 AM UTC (0e541f6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1591/49a746d...antosart:0e541f6.html" title="Last updated on May 5, 2021, 11:57 AM UTC (0e541f6)">Diff</a>
> Add CSP initialization check

- docs/index.bs
The timing when worker is started or ready are web-accessible via
the navigation timing API (https://w3c.github.io/navigation-timing/).
`workerStart` is specified to be the time when the service worker is run.
In Chromium and Gecko, `worker ready time` (exposed as `fetchStart`)
is set to the right before the time when the Fetch event can be
dispatched for the newly created worker.
In preparation for https://github.com/w3c/navigation-timing/issues/136
***
<a href="https://pr-preview.s3.amazonaws.com/noamr/ServiceWorker/pull/1575.html" title="Last updated on May 13, 2021, 11:19 AM UTC (21510d9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1575/e005153...noamr:21510d9.html" title="Last updated on May 13, 2021, 11:19 AM UTC (21510d9)">Diff</a>
> Maintain timing for worker start/ready, for navigation requests.

- docs/index.bs
This is a companion change to https://github.com/whatwg/html/pull/6677, which moves referrer policy into the policy container. As a consequence, referrer policy is taken care by the policy container mechanisms and does not need to be considered directly by ServiceWorker anymore.
***
<a href="https://pr-preview.s3.amazonaws.com/antosart/ServiceWorker/pull/1593.html" title="Last updated on May 12, 2021, 8:08 AM UTC (b0b97bc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1593/e005153...antosart:b0b97bc.html" title="Last updated on May 12, 2021, 8:08 AM UTC (b0b97bc)">Diff</a>
> Adapt to referrer policy being in policy container

- docs/index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/mfalken/ServiceWorker/pull/1598.html" title="Last updated on Jun 10, 2021, 10:12 PM UTC (c1e1ff2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1598/ff226f6...mfalken:c1e1ff2.html" title="Last updated on Jun 10, 2021, 10:12 PM UTC (c1e1ff2)">Diff</a>
> Fix typo "Serview" to "Service"

- docs/index.bs
Fixes #1407.
***
<a href="https://pr-preview.s3.amazonaws.com/Ms2ger/ServiceWorker/pull/1444.html" title="Last updated on May 25, 2021, 1:43 PM UTC (51e01b8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1444/4b5d041...Ms2ger:51e01b8.html" title="Last updated on May 25, 2021, 1:43 PM UTC (51e01b8)">Diff</a>
> Handle asynchronous modules (top-level await).

- docs/index.bs
This is an editorial PR, adapting to embedder policy moving to the policy container (https://github.com/whatwg/html/pull/6793). As a result of that, ServiceWorker does not need to mention embedder policy anymore.
> Remove embedder policy

- docs/index.bs
Follows https://github.com/whatwg/html/pull/3414.
Do not merge until that merges and has some time to make its way into the linking databases.
***
<a href="https://pr-preview.s3.amazonaws.com/domenic/ServiceWorker/pull/1602.html" title="Last updated on Jul 21, 2021, 4:10 PM UTC (d192fe1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1602/b890274...domenic:d192fe1.html" title="Last updated on Jul 21, 2021, 4:10 PM UTC (d192fe1)">Diff</a>
> Update PostMessageOptions → StructuredSerializeOptions

- docs/index.bs
In [this HTML PR](https://github.com/whatwg/html/pull/7339) we add
a `time origin` getter to the `environment settings object`.
We need to account for that value in service workers, which would be the
time the worker environment is created.
***
<a href="https://pr-preview.s3.amazonaws.com/noamr/ServiceWorker/pull/1621.html" title="Last updated on Nov 24, 2021, 3:59 PM UTC (b67daec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1621/1db9650...noamr:b67daec.html" title="Last updated on Nov 24, 2021, 3:59 PM UTC (b67daec)">Diff</a>
> Define the time origin for service workers

- docs/index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/wanderview/ServiceWorker/pull/1629.html" title="Last updated on Mar 8, 2022, 10:09 PM UTC (e9e941d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1629/d64ffd5...wanderview:e9e941d.html" title="Last updated on Mar 8, 2022, 10:09 PM UTC (e9e941d)">Diff</a>
> Partition service workers using Storage Key. (#1606)

- docs/index.bs
An attempt at fixing #1635 ("the coast is only clear…").
***
<a href="https://pr-preview.s3.amazonaws.com/tomayac/ServiceWorker/pull/1636.html" title="Last updated on Mar 28, 2022, 7:37 AM UTC (cb977d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1636/2d7be2b...tomayac:cb977d7.html" title="Last updated on Mar 28, 2022, 7:37 AM UTC (cb977d7)">Diff</a>
> Clarify code comment

- docs/index.bs
In conjunction with https://github.com/whatwg/fetch/pull/1343.
When the service worker intercepts a fetch request, the signal's abort reason must be passed to the service worker to abort the fetch controller and signal abort in https://w3c.github.io/ServiceWorker/#handle-fetch.
***
<a href="https://pr-preview.s3.amazonaws.com/nidhijaju/ServiceWorker/pull/1655.html" title="Last updated on Aug 15, 2022, 10:37 AM UTC (5689b03)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1655/adb4ef0...nidhijaju:5689b03.html" title="Last updated on Aug 15, 2022, 10:37 AM UTC (5689b03)">Diff</a>
> Abort with fetch controller's error in Handle Fetch

- docs/index.bs
Currently responses that come from service workers get encoded/decoded body size of 0.
This rectifies it.
WPT: https://github.com/web-platform-tests/wpt/pull/33283
Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=925239
Closes w3c/navigation-timing#124
***
<a href="https://pr-preview.s3.amazonaws.com/noamr/ServiceWorker/pull/1664.html" title="Last updated on Nov 28, 2022, 11:33 AM UTC (e5b8b3e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1664/5bcc30d...noamr:e5b8b3e.html" title="Last updated on Nov 28, 2022, 11:33 AM UTC (e5b8b3e)">Diff</a>
> Increment encoded/decoded body size for constructed responses

- docs/index.bs
Following on from https://github.com/w3c/ServiceWorker/pull/1672
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1674.html" title="Last updated on Mar 22, 2023, 3:56 PM UTC (a52a9bf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1674/25f60ac...a52a9bf.html" title="Last updated on Mar 22, 2023, 3:56 PM UTC (a52a9bf)">Diff</a>
> Skip executing fetch handlers if it is no-op.

- docs/index.bs
This is for stop calling Get for detecting an empty fetch listener.  Benefit of the change is that it won't execute the Javascript, and drawback is that it just ignores an empty fetch listener defined as a handleEvent property.  Since it is rare to configure the fetch event listener with the handleEvent property, not detecting empty function body for it should be negligible coverage reduction.
+@domenic
***
<a href="https://pr-preview.s3.amazonaws.com/yoshisatoyanagisawa/ServiceWorker/pull/1676.html" title="Last updated on Apr 3, 2023, 10:09 AM UTC (2ea42ac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1676/4b38437...yoshisatoyanagisawa:2ea42ac.html" title="Last updated on Apr 3, 2023, 10:09 AM UTC (2ea42ac)">Diff</a>
> Avoid executing the code in the All Fetch Listeners Are Empty algorithm.

- docs/index.bs
For https://github.com/whatwg/fetch/pull/1646.
***
<a href="https://pr-preview.s3.amazonaws.com/shaseley/ServiceWorker/pull/1678.html" title="Last updated on May 3, 2023, 9:47 PM UTC (3347d98)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1678/fb1e711...shaseley:3347d98.html" title="Last updated on May 3, 2023, 9:47 PM UTC (3347d98)">Diff</a>
> Editorial: pass signal to Request/create

- docs/index.bs
For https://github.com/whatwg/dom/issues/1194. Replaces the AbortSignal created inside of "Handle Fetch" with an AbortController, signaling abort on it instead and passing its signal when creating a Request.
***
<a href="https://pr-preview.s3.amazonaws.com/shaseley/ServiceWorker/pull/1683.html" title="Last updated on May 30, 2023, 8:41 PM UTC (3dd9c2c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1683/e8e2b81...shaseley:3dd9c2c.html" title="Last updated on May 30, 2023, 8:41 PM UTC (3dd9c2c)">Diff</a>
> Use an AbortController instead of signaling abort on AbortSignal

- docs/index.bs
Context for this is Open Web Docs people looking into automating the handling of "this feature is available only in secure contexts" banners in MDN pages. This led to the discussion with @annevk in https://github.com/w3c/webref/issues/1142#issuecomment-1927219703
When it is set, the `[SecureContext]` IDL extended attribute explicitly gives the information. That said, to avoid redundancies, that attribute is usually not set on interfaces that are exposed (through `[Exposed=xxx]`) to globals that are already restricted to secure contexts.
The Service workers spec is clear that [service workers must execute in secure contexts](https://w3c.github.io/ServiceWorker/#secure-context). However, it does not fully say so in the IDL itself. More specifically, when an interface defined in another spec …
> Flag ServiceWorkerGlobalScope as SecureContext

- .github/workflows/generate.yml
- docs/index.bs
This API allows developers to configure the routing, and allows them to offload simple things ServiceWorkers do. If the condition matches, the navigation happens without starting ServiceWorkers or executing JavaScript, which allows web pages to avoid performance penalties due to ServiceWorker interceptions.
Explainer: https://github.com/WICG/service-worker-static-routing-api
TAG review: https://github.com/w3ctag/design-reviews/issues/863
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 22, 2024, 12:13 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff …
> ServiceWorker static routing API

- docs/index.bs
Following #1701, the `install` event now uses the `InstallEvent` interface.
(FWIW, I noticed that because our spec crawler parses that table to map events with interfaces and make sure that everything's consistent)
I note that the spec also says in [section 4.4](https://w3c.github.io/ServiceWorker/#ref-for-service-worker-global-scope-install-event%E2%91%A1):
> [Service workers](https://w3c.github.io/ServiceWorker/#dfn-service-worker) have two [lifecycle events](https://w3c.github.io/ServiceWorker/#dfn-lifecycle-events), [install](https://w3c.github.io/ServiceWorker/#service-worker-global-scope-install-event) and [activate](https://w3c.github.io/ServiceWorker/#service-worker-global-scope-activate-event). [Service workers](https://w3c.github.io/ServiceWorker/#dfn-service-worker) use the …
> Update interface for install event in summary table

- docs/index.bs
Updates in the URLPattern specification was requested during the https://github.com/w3c/ServiceWorker/pull/1701 review.
The issues for the request has been resolved:
- https://github.com/whatwg/urlpattern/issues/217
- https://github.com/whatwg/urlpattern/issues/218
However, during the specification updates, the algorithm names are also updated and arguments are changed.
This is adjustments for them.
***
<a href="https://pr-preview.s3.amazonaws.com/yoshisatoyanagisawa/ServiceWorker/pull/1707.html" title="Last updated on Mar 13, 2024, 12:45 PM UTC (96233ec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1707/613f5a2...yoshisatoyanagisawa:96233ec.html" title="Last updated on Mar 13, 2024, 12:45 PM UTC (96233ec)">Diff</a>
> Editorial: Update link texts upon updates in the URLPattern specification

- docs/index.bs
Changes register to take a union of (TrustedScriptURL or USVString) rather than just a USVString.
Updates the register method steps to call Get Trusted Type compliant string
Tested in https://wpt.live/trusted-types/WorkerGlobalScope-importScripts.html
Fixes https://github.com/w3c/ServiceWorker/issues/1710
***
<a href="https://pr-preview.s3.amazonaws.com/lukewarlow/ServiceWorker/pull/1709.html" title="Last updated on Apr 22, 2024, 1:53 PM UTC (4242fab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1709/613f5a2...lukewarlow:4242fab.html" title="Last updated on Apr 22, 2024, 1:53 PM UTC (4242fab)">Diff</a>
> Upstream change from Trusted Types

- docs/index.bs
To make it clearer which controller is which, rename them to fetchController and abortController respectively.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1705.html" title="Last updated on Apr 30, 2024, 10:36 PM UTC (7730c8c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1705/8ac9c66...7730c8c.html" title="Last updated on Apr 30, 2024, 10:36 PM UTC (7730c8c)">Diff</a>
> Editorial: Rename both `controller` variables in Handle Fetch algorithm.

- docs/index.bs
This closes #1713.
Originally InstallEvent was removed in #1207, then added again in #1701, but currently it doesn't have a constructor for no reason.
***
<a href="https://pr-preview.s3.amazonaws.com/sisidovski/ServiceWorker/pull/1729.html" title="Last updated on Sep 27, 2024, 7:45 PM UTC (b8bffc9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1729/5408e2e...sisidovski:b8bffc9.html" title="Last updated on Sep 27, 2024, 7:45 PM UTC (b8bffc9)">Diff</a>
> Add constructor to InstallEvent

- docs/index.bs
The CL depends on https://github.com/whatwg/html/pull/10308 to be merged because some symbols should be exported by the HTML specification.
***
<a href="https://pr-preview.s3.amazonaws.com/yoshisatoyanagisawa/ServiceWorker/pull/1715.html" title="Last updated on May 9, 2024, 2:18 AM UTC (57d7612)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1715/8d64a5c...yoshisatoyanagisawa:57d7612.html" title="Last updated on May 9, 2024, 2:18 AM UTC (57d7612)">Diff</a>
> Editorial: fixed the bikeshed errors

- docs/index.bs
As suggested in https://github.com/w3c/ServiceWorker/issues/1747, addRoutes() checks requestMethod is valid, and matching will happens with a normalized method.
***
<a href="https://pr-preview.s3.amazonaws.com/yoshisatoyanagisawa/ServiceWorker/pull/1748.html" title="Last updated on Jan 23, 2025, 7:54 AM UTC (2f58e56)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1748/e23f928...yoshisatoyanagisawa:2f58e56.html" title="Last updated on Jan 23, 2025, 7:54 AM UTC (2f58e56)">Diff</a>
> Check requestMethod

- docs/index.bs
As covered in https://github.com/WICG/service-worker-static-routing-api?tab=readme-ov-file#how-does-it-work-if-there-is-no-fetch-handler, the fetch handler must exists not only for the "fetch-handler" source but also the "race-network-and-fetch-handler" source.  The "race-network-and-fetch-handler" source was not written in the last update.
***
<a href="https://pr-preview.s3.amazonaws.com/yoshisatoyanagisawa/ServiceWorker/pull/1719.html" title="Last updated on Jan 28, 2025, 4:18 AM UTC (5873780)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1719/4e7e0fa...yoshisatoyanagisawa:5873780.html" title="Last updated on Jan 28, 2025, 4:18 AM UTC (5873780)">Diff</a>
> Ensure "race-network-and-fetch-handler" is used with a fetch handler

- docs/index.bs
Bikeshed originally said:
>  Multiple possible 'document' dfn refs.
>  Arbitrarily chose https://dom.spec.whatwg.org/#clone-a-node-document
>  To auto-select one of the following refs, insert one of these lines into a `<pre class=link-defaults>` block:
>  spec:dom; type:dfn; for:clone a node; text:document
>  spec:dom; type:dfn; for:/; text:document
>  [=document=]
I think all of them are intended to be [=/document=] instead of [=clone a node/document=].
***
<a href="https://pr-preview.s3.amazonaws.com/yoshisatoyanagisawa/ServiceWorker/pull/1751.html" title="Last updated on Jan 29, 2025, 4:27 AM UTC (e359b0a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1751/a14460b...yoshisatoyanagisawa:e359b0a.html" title="Last updated on Jan 29, 2025, 4:27 AM UTC …
> Editorial: Fix linking errors on [=document=]

- docs/index.bs
This is a fix for https://github.com/w3c/ServiceWorker/issues/1742 and https://github.com/w3c/ServiceWorker/issues/1743.
Currently, it is technically possible to call `addRoutes()` outside of the install event.  This change follows how `FetchEvent.respondWith()` deal with the case, and prevents the `addRoutes()` method to be called outside of the install event.
At the same time, the event wait until a promise returned by `addRoutes()` resolves.
***
<a href="https://pr-preview.s3.amazonaws.com/yoshisatoyanagisawa/ServiceWorker/pull/1744.html" title="Last updated on Jan 30, 2025, 1:06 AM UTC (b8ab89e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1744/0c42aff...yoshisatoyanagisawa:b8ab89e.html" title="Last updated on Jan 30, 2025, 1:06 AM UTC …
> Allow the addRoutes() to be called during installing

- docs/index.bs
In https://github.com/w3c/ServiceWorker/issues/1746, we discussed if the spec should give guidelines about the limit of added routes, and how the user agent should behave if the added routes exceeds the limit.
We have an agreement that we're willing to pick some specific limits. This PR proposes 1024 as the total number of router conditions, and 10 as the max depth of router condition nesting level. If it exceeds those limits, the user agent throws a TypeError.
For the counting conditions part, let me clarify how we calculate the total count as this a bit tricky.
Assuming that router conditions can be nested by using `or` and `not` syntaxes. We count every sub router conditions inside the parent `or` or `not` condition, including the parent condition itself. 
Here are some examples.
```js …
```
> Add limits to the number of router rule registration

- docs/index.bs
Let me fix the following warnings by adding "-algorithm" to the ids.
```
WARNING: Multiple elements have the same id 'check-router-registration-limit':
<h3> on line 3482, <dfn> on line 3482
Deduping, but this ID may not be stable across revisions. WARNING: Multiple elements have the same id 'count-router-inner-conditions':
<h3> on line 3501, <dfn> on line 3501
Deduping, but this ID may not be stable across revisions.
```
***
<a href="https://pr-preview.s3.amazonaws.com/yoshisatoyanagisawa/ServiceWorker/pull/1753.html" title="Last updated on Feb 12, 2025, 9:09 AM UTC (ddc4199)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1753/b05ac32...yoshisatoyanagisawa:ddc4199.html" title="Last updated on Feb 12, 2025, 9:09 AM UTC (ddc4199)">Diff</a>
> Editorial: Fix bikeshed warning

- docs/index.bs
This is for addressing https://github.com/w3c/ServiceWorker/issues/1716. I also found that "not" should also be an exclusive condition. Let me update.
***
<a href="https://pr-preview.s3.amazonaws.com/yoshisatoyanagisawa/ServiceWorker/pull/1754.html" title="Last updated on Feb 14, 2025, 7:24 AM UTC (ed07464)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1754/b8255db...yoshisatoyanagisawa:ed07464.html" title="Last updated on Feb 14, 2025, 7:24 AM UTC (ed07464)">Diff</a>
> Editorial: fix typo around "mutual exclusive"

- docs/index.bs
This is for addressing https://github.com/w3c/ServiceWorker/issues/1758 that fixes broken links fragments and updates redirects as a result of [validator](https://validator.w3.org/checklink?uri=https%3A%2F%2Fwww.w3.org%2FTR%2F2025%2FCRD-service-workers-20250306%2F&hide_type=all&recursive=on&depth=&check=Check)
***
<a href="https://pr-preview.s3.amazonaws.com/monica-ch/ServiceWorker/pull/1760.html" title="Last updated on Mar 19, 2025, 8:25 PM UTC (376e647)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1760/b8255db...monica-ch:376e647.html" title="Last updated on Mar 19, 2025, 8:25 PM UTC (376e647)">Diff</a>
> Editorial:  Fix broken links/fragments

- docs/index.bs
This addresses https://github.com/w3c/ServiceWorker/issues/1765.
As pointed out, the line lacks a space.  Let me add.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1766.html" title="Last updated on Apr 27, 2025, 11:43 PM UTC (8763265)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1766/4f070e8...8763265.html" title="Last updated on Apr 27, 2025, 11:43 PM UTC (8763265)">Diff</a>
> Editorial: Add a space between following and perform the fetch hook

- docs/index.bs
As mentioned in https://github.com/w3c/ServiceWorker/issues/1472, https://w3c.github.io/ServiceWorker/#resolve-job-promise-algorithm is written to return Promise<ServiceWorkerRegistration>. Also, according to https://wpt.fyi/results/service-workers/service-worker/update-result.https.html?label=experimental&label=master&aligned, all implementations are actually returning a `Promise<ServiceWorkerRegistration>`.
***
<a href="https://pr-preview.s3.amazonaws.com/yoshisatoyanagisawa/ServiceWorker/pull/1767.html" title="Last updated on May 1, 2025, 2:24 AM UTC (6495b0f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1767/479b8ae...yoshisatoyanagisawa:6495b0f.html" title="Last updated on May 1, 2025, 2:24 AM UTC (6495b0f)">Diff</a>
> Correct ServiceWorkerRegistration Web IDL

- docs/index.bs
This PR fixes the handle fetch algorithm to check the nullness of Get Router Source (`source`)
***
<a href="https://pr-preview.s3.amazonaws.com/quasi-mod/ServiceWorker/pull/1768.html" title="Last updated on May 7, 2025, 5:12 AM UTC (3aef8b9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1768/0a2f29f...quasi-mod:3aef8b9.html" title="Last updated on May 7, 2025, 5:12 AM UTC (3aef8b9)">Diff</a>
> Update handle fetch algorithm step to consider null of source

- docs/index.bs
This PR adds the new fields for the static routing API and the getter steps. This will be later exposed to the resource timing API. It has been discussed in https://github.com/w3c/resource-timing/issues/389.
***
<a href="https://pr-preview.s3.amazonaws.com/quasi-mod/ServiceWorker/pull/1769.html" title="Last updated on May 28, 2025, 1:58 AM UTC (ca79de3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1769/b7bbcea...quasi-mod:ca79de3.html" title="Last updated on May 28, 2025, 1:58 AM UTC (ca79de3)">Diff</a>
> Add new fields and getter steps for static routing resource timing

- docs/index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/quasi-mod/ServiceWorker/pull/1772.html" title="Last updated on May 28, 2025, 8:03 AM UTC (8d3f4ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1772/ca38db9...quasi-mod:8d3f4ba.html" title="Last updated on May 28, 2025, 8:03 AM UTC (8d3f4ba)">Diff</a>
> Update Handle Fetch to return timing info

- docs/index.bs
A minor editorial fix to clarify that the Create Fetch Event and Dispatch algorithm may return null.
***
<a href="https://pr-preview.s3.amazonaws.com/sisidovski/ServiceWorker/pull/1778.html" title="Last updated on Jun 11, 2025, 2:57 AM UTC (b3102a8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1778/1d795e2...sisidovski:b3102a8.html" title="Last updated on Jun 11, 2025, 2:57 AM UTC (b3102a8)">Diff</a>
> Editorial: the Create Fetch Event and Dispatch output returns null

- docs/index.bs
This pull request originates from the work proposed by @monica-ch in w3c/ServiceWorker#1764, but has been extensively reworked based on review feedback.
This PR corrects response handling for race-network-and-fetch-handler.
**Primary Fix:** The handler now correctly uses the actual fetch response for |raceResponse| instead of a generic [=network error=].
**Minor Improvement:** |timingInfo| is now included in the [=network error=], when returned by [=Create Fetch Event and Dispatch=], which simplifies the calling code.
***
<a href="https://pr-preview.s3.amazonaws.com/yoshisatoyanagisawa/ServiceWorker/pull/1777.html" title="Last updated on Jun 12, 2025, 10:51 AM UTC (51832d8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1777/ef029c5...yoshisatoyanagisawa:5183 …
> Fix: race-network-and-fetch-handler now uses actual |raceResponse|

- docs/index.bs
This is a follow up of https://github.com/w3c/ServiceWorker/pull/1777#discussion_r2141544666.
It originally https://github.com/w3c/ServiceWorker/pull/1779, but closed by mistake.
https://infra.spec.whatwg.org/#abort-when adds the check each time the step is executed. However, there is only a step between and the abort-when and if-aborted, it should be less effective abort than we expect. Let me add a step inside the callback in case.
***
<a href="https://pr-preview.s3.amazonaws.com/yoshisatoyanagisawa/ServiceWorker/pull/1780.html" title="Last updated on Jun 18, 2025, 5:18 AM UTC (153f7fb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1780/a402c93...yoshisatoyanagisawa:153f7fb.html" title="Last updated on Jun 18, 2025, 5:18 AM UTC (153f7fb)">Diff</a>
> Less fragile |fetchController| termination check

- docs/index.bs
This is the PR to support [ServiceWorkerAutoPreload](https://github.com/explainers-by-googlers/service-worker-auto-preload).
ServiceWorkerAutoPreload is defined as an optional browser optimization so that the browser minimizes the cost of the bootstrap by dispatching the navigational network request before starting the service worker. The dispatched network request is consumed by `fetch(e.request)` in the fetch handler after the bootstrap, or consumed by the client as a fallback request if the fetch handler doesn't call `respondWith()`.
The developer can disable this optimization by opting out via setting the router rule provided by the static routing API.  Specifically, the router source "network" works as an opt-out signal.
Please read [the …
> ServiceWorkerAutoPreload

- docs/index.bs
QuotaExceededError is graduating from being a DOMException name into a new error class, in https://github.com/whatwg/webidl/pull/1465. Update creation sites to reflect this.
For now, the quota and requested properties are left at their default (null). Future work could include setting them in an informative fashion.
***
<a href="https://pr-preview.s3.amazonaws.com/domenic/ServiceWorker/pull/1782.html" title="Last updated on Jul 8, 2025, 4:38 AM UTC (b3968ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1782/3d83bed...domenic:b3968ee.html" title="Last updated on Jul 8, 2025, 4:38 AM UTC (b3968ee)">Diff</a>
> Update QuotaExceededError usage

- docs/index.bs
This change corrects the cache resolution logic within the Handle Fetch algorithm when the router source is RouterSourceEnum/"cache".
The Problem:
Previously, the algorithm always used reservedClient to resolve the storage key, regardless of the request type. However, reservedClient is only valid for top-level navigation requests and is not available for subresource requests. This could lead to accessing the incorrect cache storage during subresource fetches.
The Fix:
Logic has been added to differentiate between a non-subresource request and a subresource request.
- For a non-subresource request: It continues to use reservedClient as before.
- For a subresource request: It now uses the client associated with the request object.
This ensures that the correct storage key, based on the …
> Handle Fetch: Use correct storage key for subresource requests

- docs/index.bs
This commit clarifies how the Cache API interacts with the underlying storage mechanism, resolving ambiguity that stemmed from previous specification language.
Key changes:
- Removes the direct association between "storage key" and "name to cache map".
- Defines "relevant name to cache map" as being retrieved via the `obtain a local storage bottle map` algorithm from the Storage specification, ensuring alignment.
- Updates the definition of `CacheStorage` to represent the `name to cache map` associated with its `environment settings object`, rather than the `origin`.
This makes the relationship between the ServiceWorker Cache API and the Storage specification explicit and consistent, addressing the core issue raised in https://github.com/w3c/ServiceWorker/issues/1784 and the follow-up …
> Fix: Align Cache API definitions with Storage spec
