- explainer.md
The main change is from "imperative-only" to "declarative-only" in the first sentence, with a few extra alterations as I found the "Having failed serially in many of the same ways" part difficult to follow.
Feel free to rewrite/discard! :)
> Suggested edits to paragraph about declarative-only solutions

- spec/service_worker/index.html
This adds a number of auto-links that were missing and seems to change the syntax highlighting.
This was done using
```
curl https://api.csswg.org/bikeshed/ -f -F file=@index.bs > index.html
```
to ensure it's the very latest.
> Run the latest Bikeshed

- explainer.md
The current one leads to a 404 page.
> Update link to caching API

- docs/index.bs
- docs/index.html
> Editorial: export Handle Functional Event

- explainer.md
> Revert "Fix incomplete link"

- docs/index.bs
- docs/index.html
I also did the same for the header. I assume we handle booleans the same way there?
> Correcting usecache attribute. Fixes #1069

- w3c.json
cf https://w3c.github.io/w3c.json.html
> Update w3c.json to reflect new Working Group

- docs/index.bs
- docs/v1/index.bs
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/ServiceWorker/grammar-fix.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/ServiceWorker/f908584...cf7ab47.html)
> Minor grammar issue. Fixes #1214.

- docs/index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/bocoup/ServiceWorker/pull/1244.html" title="Last updated on Dec 8, 2017, 9:58 PM GMT (53c375a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1244/7df02a4...bocoup:53c375a.html" title="Last updated on Dec 8, 2017, 9:58 PM GMT (53c375a)">Diff</a>
> Correct typo

- docs/index.html
@jungkees @jakearchibald The compiled spec looks out-of-date. I re-ran compile.sh.
> Building Spec: 9a6b738771d1e3d235b539bbdc896e88803573e8

- docs/index.bs
- docs/index.html
@jakearchibald
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/ServiceWorker/pull/1343.html" title="Last updated on Aug 10, 2018, 5:35 PM GMT (9268cd9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1343/8e6e33b...jyasskin:9268cd9.html" title="Last updated on Aug 10, 2018, 5:35 PM GMT (9268cd9)">Diff</a>
> Fix #1339: Resolve preloadResponse with a Response object.

- docs/index.bs
- docs/v1/index.bs
@jakearchibald, I didn't find these while reviewing.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1354.html" title="Last updated on Sep 12, 2018, 10:45 PM GMT (388661f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1354/243f3b3...388661f.html" title="Last updated on Sep 12, 2018, 10:45 PM GMT (388661f)">Diff</a>
> Remove unused variables

- docs/index.bs
This is to fix #1383 and #1382.
If it's ok, I'll update v1 too.
cc @ytausky.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1384.html" title="Last updated on Jan 30, 2019, 11:36 PM UTC (b462a94)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1384/f0bd826...b462a94.html" title="Last updated on Jan 30, 2019, 11:36 PM UTC (b462a94)">Diff</a>
> Correcting the use of types and simplifying the response body read.

- README.md
Minor update to the README to increase readability.
I inserted a newline between "Risk labels for impacts MVP issues" and added bullet points in various places.
Minor point, but it kind of bothered me while reading this 😄
> Minor Readme format changes

- docs/index.bs
- docs/v1/index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1413.html" title="Last updated on Jun 3, 2019, 7:53 AM UTC (f1c9d7a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1413/c1f3619...f1c9d7a.html" title="Last updated on Jun 3, 2019, 7:53 AM UTC (f1c9d7a)">Diff</a>
> Fixing link to "scope" and copying changes to v1.

- docs/index.bs
- docs/v1/index.bs
Fixes a mistake from #1417.
***
<a href="https://pr-preview.s3.amazonaws.com/mattto/ServiceWorker/pull/1418.html" title="Last updated on Jun 6, 2019, 3:50 AM UTC (cd5af05)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1418/2f71190...mattto:cd5af05.html" title="Last updated on Jun 6, 2019, 3:50 AM UTC (cd5af05)">Diff</a>
> Fix early return value from Handle Fetch.

- docs/index.bs
- docs/v1/index.bs
Fixes #1423
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1424.html" title="Last updated on Jun 7, 2019, 8:36 AM UTC (2f3e32c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1424/4a50271...2f3e32c.html" title="Last updated on Jun 7, 2019, 8:36 AM UTC (2f3e32c)">Diff</a>
> Fixing max scope to include trailing slash.

- docs/index.bs
- docs/v1/index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1425.html" title="Last updated on Jun 7, 2019, 11:28 AM UTC (82b3e2b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1425/2c6fa22...82b3e2b.html" title="Last updated on Jun 7, 2019, 11:28 AM UTC (82b3e2b)">Diff</a>
> Fixing a couple of bikeshed errors

- docs/index.bs
- docs/v1/index.bs
Fixes #1363.
Fixes #1461.
***
<a href="https://pr-preview.s3.amazonaws.com/Ms2ger/ServiceWorker/pull/1463.html" title="Last updated on Sep 2, 2019, 11:18 AM UTC (1ea9bb4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1463/4783e9d...Ms2ger:1ea9bb4.html" title="Last updated on Sep 2, 2019, 11:18 AM UTC (1ea9bb4)">Diff</a>
> Editorial: Update 'wait for all' usage.

- docs/index.bs
- docs/v1/index.bs
Fixing a few broken references & bikeshed warnings.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1466.html" title="Last updated on Sep 2, 2019, 11:21 AM UTC (6a6e007)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1466/4783e9d...6a6e007.html" title="Last updated on Sep 2, 2019, 11:21 AM UTC (6a6e007)">Diff</a>
> Fixing refs

- docs/index.bs
- docs/v1/index.bs
https://github.com/heycam/webidl/pull/792 landed.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1467.html" title="Last updated on Sep 4, 2019, 5:13 PM UTC (f5a3df7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1467/7187b87...f5a3df7.html" title="Last updated on Sep 4, 2019, 5:13 PM UTC (f5a3df7)">Diff</a>
> Updating use of promises

- docs/index.bs
- docs/v1/index.bs
Fixes #1464. Cc @Ms2ger.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1470.html" title="Last updated on Sep 10, 2019, 7:27 AM UTC (b5d33ca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1470/667ba40...b5d33ca.html" title="Last updated on Sep 10, 2019, 7:27 AM UTC (b5d33ca)">Diff</a>
> Updating constructor definitions

- docs/index.bs
- docs/v1/index.bs
I think this matches what browsers actually do.
Fixes #1477.
Tests incoming…
cc @youennf @asutherland @cdumez @Yannic
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1487.html" title="Last updated on Dec 6, 2019, 2:33 PM UTC (0361f72)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1487/ffdd6c0...0361f72.html" title="Last updated on Dec 6, 2019, 2:33 PM UTC (0361f72)">Diff</a>
> Fixing ready promise definition

- docs/index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/tingshao/ServiceWorker/pull/1496.html" title="Last updated on Jan 22, 2020, 4:37 AM UTC (05328eb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1496/910cdd8...tingshao:05328eb.html" title="Last updated on Jan 22, 2020, 4:37 AM UTC (05328eb)">Diff</a>
> Add FetchEvent.handled (#1397)

- docs/index.bs
Addresses #1549
***
<a href="https://pr-preview.s3.amazonaws.com/mfalken/ServiceWorker/pull/1572.html" title="Last updated on Mar 25, 2021, 5:43 AM UTC (2f7989b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1572/414e78c...mfalken:2f7989b.html" title="Last updated on Mar 25, 2021, 5:43 AM UTC (2f7989b)">Diff</a>
> Explain message and messageerror for ServiceWorkerContainer.

- docs/index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/Ms2ger/ServiceWorker/pull/1599.html" title="Last updated on Jun 11, 2021, 11:45 AM UTC (e2d881e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1599/9c77873...Ms2ger:e2d881e.html" title="Last updated on Jun 11, 2021, 11:45 AM UTC (e2d881e)">Diff</a>
> Editorial: Fix ThrowCompletion link.

- docs/index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/wanderview/ServiceWorker/pull/1630.html" title="Last updated on Mar 10, 2022, 3:09 PM UTC (9f92e16)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1630/7ad2f80...wanderview:9f92e16.html" title="Last updated on Mar 10, 2022, 3:09 PM UTC (9f92e16)">Diff</a>
> Partition cache API by storage key. (#1606)

- docs/index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/wanderview/ServiceWorker/pull/1632.html" title="Last updated on Mar 10, 2022, 7:01 PM UTC (386e63f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1632/7ad2f80...wanderview:386e63f.html" title="Last updated on Mar 10, 2022, 7:01 PM UTC (386e63f)">Diff</a>
> Partition clients API by storage key. (#1606)

- docs/index.bs
As per https://github.com/whatwg/html/pull/9755.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/pull/1693.html" title="Last updated on Sep 19, 2023, 3:09 PM UTC (c76ffe1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1693/89695bb...c76ffe1.html" title="Last updated on Sep 19, 2023, 3:09 PM UTC (c76ffe1)">Diff</a>
> Editorial: remove API URL character encoding

- CONTRIBUTING.md
- docs/index.bs
- w3c.json
***
<a href="https://pr-preview.s3.amazonaws.com/siusin/ServiceWorker/pull/1759.html" title="Last updated on Mar 6, 2025, 9:46 AM UTC (6d1b2eb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1759/1d795e2...siusin:6d1b2eb.html" title="Last updated on Mar 6, 2025, 9:46 AM UTC (6d1b2eb)">Diff</a>
> move the repo to WebAppsWG
